
/* Minimalized app.js for AgroLink v6 - core logic */
const STORAGE = { users:'agrolink_v6_users', current:'agrolink_v6_current', posts:'agrolink_v6_posts', proposals:'agrolink_v6_proposals', freelancers:'agrolink_v6_freelancers', market:'agrolink_v6_market', diags:'agrolink_v6_diags', ranking:'agrolink_v6_ranking', theme:'agrolink_v6_theme' };
function $(s){return document.querySelector(s);} function save(k,v){localStorage.setItem(k,JSON.stringify(v));} function load(k,d){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d));}catch(e){return d;}} function escapeHtml(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}
if(!localStorage.getItem(STORAGE.posts)) save(STORAGE.posts,[{id:'ps1',user:'João (MG)',text:'Alguém com experiência em gotejo para uva?',img:'images/irrigacao.png',likes:5,comments:[]},{id:'ps2',user:'Maria (BA)',text:'Dicas para reduzir mastite no rebanho?',img:'images/gado.png',likes:8,comments:[]}]);
if(!localStorage.getItem(STORAGE.market)) save(STORAGE.market,[{id:'m1',title:'Trator 75hp',seller:'AgroMáquinas',price:'R$85.000',contact:'contato@agromaq.com',img:'images/tractor.png'},{id:'m2',title:'Drone pulverizador 10L',seller:'DroneAgro',price:'R$18.500',contact:'vendas@droneagro.com',img:'images/drone.png'}]);
if(!localStorage.getItem(STORAGE.proposals)) save(STORAGE.proposals,[]); if(!localStorage.getItem(STORAGE.freelancers)) save(STORAGE.freelancers,[]); if(!localStorage.getItem(STORAGE.diags)) save(STORAGE.diags,[]); if(!localStorage.getItem(STORAGE.ranking)) save(STORAGE.ranking,{});
// Themes
function applyTheme(t){ if(t==='auto'){ const prefersDark = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches; document.body.classList.toggle('theme-dark', prefersDark); } else { document.body.classList.toggle('theme-dark', t==='dark'); } localStorage.setItem(STORAGE.theme,t); updateThemeButton(); } function cycleTheme(){ const cur = localStorage.getItem(STORAGE.theme)||'auto'; const order=['auto','light','dark']; const next = order[(order.indexOf(cur)+1)%order.length]; applyTheme(next); } function updateThemeButton(){ const cur = localStorage.getItem(STORAGE.theme)||'auto'; const btn = document.getElementById('theme-btn'); if(!btn) return; btn.textContent = cur==='auto'? 'Tema: Auto' : (cur==='dark'? 'Tema: Escuro' : 'Tema: Claro'); }
// Login/signup
function showLogin(){ document.getElementById('login-card').style.display='block'; document.getElementById('main-card').style.display='none'; const cur = load(STORAGE.current,null); if(cur) openPortal(cur); }
function openPortal(user){ document.getElementById('login-card').style.display='none'; document.getElementById('main-card').style.display='block'; document.getElementById('welcome-name').textContent = 'Olá, ' + user.name.split(' ')[0] + ' — ' + (user.prod.join(', ')||'Produtor'); save(STORAGE.current,user); renderAll(); }
function submitSignup(){ const name=$('#signup-name').value.trim(); const cpf=$('#signup-cpf').value.trim(); const phone=$('#signup-phone').value.trim(); const city=$('#signup-city').value.trim(); const state=$('#signup-state').value; const prod=Array.from(document.querySelectorAll('input[name="prod"]:checked')).map(x=>x.value); if(!name||!cpf) return alert('Nome e CPF são obrigatórios.'); const users = load(STORAGE.users,[]); const user={id:'u'+Date.now(),name,cpf,phone,city,state,prod}; users.push(user); save(STORAGE.users,users); openPortal(user); }
function submitLogin(){ const cpf=$('#login-cpf').value.trim(); if(!cpf) return alert('Digite CPF/CNPJ para entrar.'); const users = load(STORAGE.users,[]); const u = users.find(x=>x.cpf===cpf); if(u) return openPortal(u); alert('Usuário não encontrado.'); }
// Feed
function renderFeed(){ const feed = $('#feed'); feed.innerHTML=''; const posts = load(STORAGE.posts,[]).slice().reverse(); posts.forEach(p=>{ const el=document.createElement('div'); el.className='post-card'; el.innerHTML = `<img src="${p.img||'images/bg_hero_1.png'}"><div style="flex:1"><strong>${escapeHtml(p.user)}</strong><div class="small" style="margin-top:6px">${escapeHtml(p.text)}</div><div style="margin-top:8px"><button class="btn" onclick="likePost('${p.id}')">❤️ ${p.likes||0}</button> <button class="btn" onclick="openComments('${p.id}')">💬 Comentários</button></div></div>`; feed.appendChild(el); }); }
function addPost(){ const text = $('#post-text').value.trim(); if(!text) return alert('Escreva algo antes.'); const posts = load(STORAGE.posts,[]); const cur = load(STORAGE.current,null)||{name:'Visitante'}; const id = 'ps'+Date.now(); posts.push({id,user: cur.name+' ('+(cur.state||'--')+')',text,img:'images/bg_hero_1.png',likes:0,comments:[]}); save(STORAGE.posts,posts); $('#post-text').value=''; addPointsForAction(cur,2); renderFeed(); }
function likePost(id){ const posts=load(STORAGE.posts,[]); const p=posts.find(x=>x.id===id); if(!p) return; p.likes=(p.likes||0)+1; save(STORAGE.posts,posts); addPointsForAction(load(STORAGE.current,null),1); renderFeed(); }
function openComments(id){ const posts = load(STORAGE.posts,[]); const p = posts.find(x=>x.id===id); if(!p) return alert('Post não encontrado.'); const txt = prompt('Adicionar comentário:'); if(txt){ p.comments = p.comments||[]; p.comments.push({by:(load(STORAGE.current,null)||{name:'Visitante'}).name, text:txt}); save(STORAGE.posts,posts); addPointsForAction(load(STORAGE.current,null),1); renderFeed(); } }
// Proposals and Freelancers
function renderProposals(){ const list = $('#proposals-list'); list.innerHTML=''; const arr = load(STORAGE.proposals,[]); if(arr.length===0){ list.innerHTML='<div class="small">Nenhuma proposta.</div>'; return; } arr.slice().reverse().forEach(p=>{ const d=document.createElement('div'); d.className='card'; d.style.marginBottom='8px'; d.innerHTML = `<strong>${escapeHtml(p.title)}</strong><div class='small'>${escapeHtml(p.type)} • ${escapeHtml(p.region)} • R$ ${escapeHtml(p.price||'--')}</div><div style='margin-top:6px'>${escapeHtml(p.desc)}</div><div style='margin-top:8px'><button class='btn' onclick="contact('${escapeHtml(p.contact||'--')}')">Contactar</button></div>`; list.appendChild(d); }); }
function submitProposal(){ const title=$('#proposal-title').value.trim(); const type=$('#proposal-type').value; const region=$('#proposal-region').value.trim(); const price=$('#proposal-price').value.trim(); const desc=$('#proposal-desc').value.trim(); const contact=$('#proposal-contact').value.trim(); if(!title) return alert('Preencha título.'); const arr=load(STORAGE.proposals,[]); arr.push({id:'pr'+Date.now(),title,type,region,price,desc,contact}); save(STORAGE.proposals,arr); renderProposals(); addPointsForAction(load(STORAGE.current,null),3); }
// Freelancers
function renderFreelancers(){ const list = $('#freelancers-list'); list.innerHTML=''; const arr = load(STORAGE.freelancers,[]); if(arr.length===0){ list.innerHTML='<div class="small">Nenhum freelancer inscrito.</div>'; return; } arr.slice().reverse().forEach(f=>{ const d=document.createElement('div'); d.className='profile-card'; d.innerHTML = `<div class='avatar-sm'>${escapeHtml(f.name.split(' ')[0].slice(0,2))}</div><div style='flex:1'><strong>${escapeHtml(f.name)}</strong><div class='small'>${escapeHtml(f.area)} • ${escapeHtml(f.level)}</div><div class='small' style='margin-top:6px'>${escapeHtml(f.bio)}</div></div><div style='text-align:right'><button class='btn' onclick="contact('${escapeHtml(f.contact||'--')}')">Contactar</button></div>`; list.appendChild(d); }); }
function submitFreelancer(){ const name=$('#free-name').value.trim(); const area=$('#free-area').value.trim(); const level=$('#free-level').value; const bio=$('#free-bio').value.trim(); const contact=$('#free-contact').value.trim(); if(!name||!area) return alert('Preencha nome e área.'); const arr=load(STORAGE.freelancers,[]); arr.push({id:'f'+Date.now(),name,area,level,bio,contact}); save(STORAGE.freelancers,arr); renderFreelancers(); addPointsForAction(load(STORAGE.current,null),5); $('#free-name').value=''; $('#free-area').value=''; $('#free-bio').value=''; $('#free-contact').value=''; }
// Market
function renderMarket(){ const grid = $('#market-grid'); grid.innerHTML=''; const items = load(STORAGE.market,[]); items.forEach(it=>{ const d = document.createElement('div'); d.className='card'; d.style.padding='10px'; d.style.marginBottom='8px'; d.innerHTML = `<img src="${it.img}" style="width:100%;height:120px;object-fit:cover;border-radius:8px"><strong style="display:block;margin-top:8px">${escapeHtml(it.title)}</strong><div class="small">${escapeHtml(it.seller)} • ${escapeHtml(it.price)}</div><div style="margin-top:8px"><button class="btn" onclick="contact('${escapeHtml(it.contact)}')">Contactar</button></div>`; grid.appendChild(d); }); }
// Diagnostic
function runPrediagnosis(){ const name=$('#diag-name').value.trim(); const city=$('#diag-city').value.trim(); const act=$('#diag-activity').value; const problem=$('#diag-problem').value.trim().toLowerCase(); const area=parseFloat($('#diag-area').value)||0; const soil=$('#diag-soil').value; if(!name||!city) return alert('Preencha nome e município.'); let score=0; const issues=[]; if(problem.includes('seca')||problem.includes('seco')){score+=2;issues.push('Possível falta de água/irrigação.');} if(problem.includes('praga')||problem.includes('lagarta')||problem.includes('pulgão')){score+=2;issues.push('Monitorar pragas; considerar controle integrado.');} if(problem.includes('queda')||problem.includes('perda')||problem.includes('baixa')){score+=1;issues.push('Produtividade reduzida; avaliar nutrição.');} if(soil==='nao'){score+=1;issues.push('Sem análise de solo: recomenda-se coleta.');} if(area>50){score+=1;issues.push('Área grande: planejar por talhões.');} let severity='Baixa'; if(score>=4) severity='Alta'; else if(score>=2) severity='Média'; const recs=issues.slice(); if(act==='uva') recs.push('Uva: pH 6.0-7.0; prefira gotejo.'); if(act==='bovino') recs.push('Bovino: avalie pastagem e calendário sanitário.'); if(recs.length===0) recs.push('Dados insuficientes — envie mais detalhes.'); const result={producer:name,city,activity:act,severity,recommendations:recs,date:new Date().toLocaleString()}; const arr=load(STORAGE.diags,[]); arr.push(result); save(STORAGE.diags,arr); $('#diag-result').innerHTML = `<div class='card'><strong>Prediagnóstico: ${result.severity}</strong><div class='small'>Produtor: ${result.producer} • ${result.city} • Atividade: ${result.activity}</div><ul>${result.recommendations.map(r=>'<li>'+r+'</li>').join('')}</ul><div style='margin-top:8px'><button class='btn' onclick='shareDiagnosis()'>Compartilhar Resultado</button></div></div>`; addPointsForAction(load(STORAGE.current,null),3); }
function shareDiagnosis(){ const arr=load(STORAGE.diags,[]); if(!arr.length) return alert('Nenhum diagnóstico disponível.'); const last=arr[arr.length-1]; const text=`Prediagnóstico (${last.date}): ${last.producer} - ${last.city} - Atividade: ${last.activity} - Severidade: ${last.severity}. Recomendações: ${last.recommendations.join('; ')}`; navigator.clipboard?.writeText(text); alert('Resumo copiado para área de transferência.'); }
// Assistant (simple)
function assistantReply(q){ const text=q.toLowerCase(); const map=[{k:['uva','videira'],r:['Uvas preferem solo drenado, pH 6-7. Evite encharcar.','Poda e irrigação no florescimento ajudam no calibre.']},{k:['gado','bovino','boi'],r:['Bovinos: rotação de pastos e calendário vacinal.','Monitore parasitas e planeje suplementação.']},{k:['porco','suín'],r:['Suínos: ambiente controlado e biossegurança.','Alimentação por fase melhora desempenho.']},{k:['ave','frango','galinha'],r:['Aves: ventilação, densidade e vacinação.','Biossegurança reduz surtos.']},{k:['irrig','gotejo'],r:['Gotejo economiza água e reduz doenças foliares.','Use sensores para otimizar irrigação.']},{k:['solo','ph','calcario'],r:['Faça análise de solo e aplique calcário conforme laudo.','Matéria orgânica melhora estrutura.']},{k:['praga','lagarta','pulgão'],r:['Monitore com armadilhas e use controle integrado.','Identifique praga antes de aplicar químico.']}] ; for(const m of map){ for(const kw of m.k){ if(text.includes(kw)) return m.r[Math.floor(Math.random()*m.r.length)]; } } return 'Descreva espécie, local e sintomas para dica prática.'; }
document.getElementById('ask-btn')?.addEventListener('click', ()=>{ const q=$('#assist-q').value.trim(); if(!q) return; const messages=$('#messages'); const user=document.createElement('div'); user.className='msg user'; user.textContent=q; messages.appendChild(user); const loader=document.createElement('div'); loader.className='msg'; loader.textContent='Pensando...'; messages.appendChild(loader); setTimeout(()=>{ loader.remove(); const reply=assistantReply(q); const rdiv=document.createElement('div'); rdiv.className='msg'; rdiv.textContent=reply; messages.appendChild(rdiv); messages.scrollTop=messages.scrollHeight; $('#assist-q').value=''; addPointsForAction(load(STORAGE.current,null),2); },700); });
function contact(info){ navigator.clipboard?.writeText(info); alert('Contato copiado: '+info); addPointsForAction(load(STORAGE.current,null),1); }
// Points and ranking
function addPointsForAction(user,pts){ if(!user) return; const rank = load(STORAGE.ranking,{}); rank[user.id] = (rank[user.id]||0) + (pts||0); save(STORAGE.ranking,rank); renderRanking(); }
function renderRanking(){ const container = document.getElementById('ranking-list'); if(!container) return; container.innerHTML=''; const rank = load(STORAGE.ranking,{}); const users = load(STORAGE.users,[]); const arr = Object.entries(rank).map(([id,pts])=>{ const u = users.find(x=>x.id===id); return {id,pts,name: u?u.name:'Usuário'} }); arr.sort((a,b)=>b.pts-a.pts); arr.slice(0,10).forEach(r=>{ const div=document.createElement('div'); div.className='rank-item'; div.innerHTML = `<div>${escapeHtml(r.name)}</div><div><strong>${r.pts} pts</strong></div>`; container.appendChild(div); }); }
// Gallery
function renderGallery(){ const g = document.getElementById('gallery'); if(!g) return; g.innerHTML=''; const imgs=['bg_hero_1.png','bg_hero_2.png','bg_hero_3.png','bg_hero_4.png','pasto.png','gado.png','porco.png','aves.png','colmeia.png','irrigacao.png','drone.png','uva.png','manga.png','morango.png','solo.png','tractor.png']; imgs.forEach(n=>{ const i=document.createElement('img'); i.src='images/'+n; i.alt=n; g.appendChild(i); }); renderThumbs(); } function renderThumbs(){ const t=document.getElementById('thumbs'); if(!t) return; t.innerHTML=''; ['pasto.png','gado.png','porco.png','aves.png','colmeia.png','irrigacao.png','drone.png','tractor.png'].forEach(n=>{ const i=document.createElement('img'); i.src='images/'+n; i.alt=n; t.appendChild(i); }); }
// init
applyTheme(localStorage.getItem(STORAGE.theme)||'auto'); renderFeed(); renderNews = function(){ document.getElementById('news-list').innerHTML = '<div class="small">Notícias fictícias: Feira regional; Programa estadual; Exportações em alta.</div>'; }; renderProposals = renderProposals || function(){}; renderFreelancers = renderFreelancers || function(){}; renderMarket = renderMarket || function(){}; renderGallery(); renderRanking();
// Expose some functions
window.submitSignup = submitSignup; window.submitLogin = submitLogin; window.addPost = addPost; window.likePost = likePost; window.openComments = openComments; window.submitProposal = submitProposal; window.submitFreelancer = submitFreelancer; window.renderProposals = renderProposals; window.renderFreelancers = renderFreelancers; window.contact = contact; window.renderMarket = renderMarket; window.runPrediagnosis = runPrediagnosis; window.shareDiagnosis = shareDiagnosis; window.renderGallery = renderGallery; window.renderFeed = renderFeed; window.cycleTheme = cycleTheme; window.renderRanking = renderRanking; window.addPointsForAction = addPointsForAction;
